version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    working_dir: /app
    ports:
      - 5555:5555
    environment:
      PORT: 5555
    stdin_open: true
    tty: true
